export const mock = [
    {
        "id": "slide-1",
        "nation": "U.S.S.R.",
        "quantity": "141",
        "type": "U.S.S.R. vehicles in the game",
        "technic": ["Т-34", "IS", "IS-7", "KV-1", "ISU-152"],
        "imgFlag": "sliderWot/assets/nation/USSR/ussr-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/USSR/ussr-flag.webp",
        "imgTanks": "sliderWot/assets/nation/USSR/ussr-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/USSR/ussr-tanks.webp",
        "altTanks": "Soviet cars in the game",
        "imgPagin": "sliderWot/assets/nation/USSR/ussr-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/USSR/ussr-flag_pag.webp"
    },
    {
        "id": "slide-2",
        "nation": "Germany",
        "quantity": "128",
        "type": "German vehicles in the game",
        "technic": ["StuG III", "Panther", "Maus", "Tiger", "Pz. III"],
        "imgFlag": "sliderWot/assets/nation/Germany/germany-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Germany/germany-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Germany/germany-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Germany/germany-tanks.webp",
        "altTanks": "German cars in the game",
        "imgPagin": "sliderWot/assets/nation/Germany/germany-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Germany/germany-flag_pag.webp"
    },
    {
        "id": "slide-3",
        "nation": "U.S.A.",
        "quantity": "109",
        "type": "U.S.A. vehicles in the game",
        "technic": ["Sherman", "Pershing", "Patton", "T32", "Hellcat"],
        "imgFlag": "sliderWot/assets/nation/USA/usa-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/USA/usa-flag.webp",
        "imgTanks": "sliderWot/assets/nation/USA/usa-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/USA/usa-tanks.webp",
        "altTanks": "American cars in the game",
        "imgPagin": "sliderWot/assets/nation/USA/usa-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/USA/usa-flag_pag.webp"
    },
    {
        "id": "slide-4",
        "nation": "France",
        "quantity": "78",
        "type": "French vehicles in the game",
        "technic": ["AMX 13 75", "AMX 30 B", "Bat.-Châtillon 25 t", "Lorraine 40 t", "Foch B"],
        "imgFlag": "sliderWot/assets/nation/France/france-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/France/france-flag.webp",
        "imgTanks": "sliderWot/assets/nation/France/france-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/France/france-tanks.webp",
        "altTanks": "French cars in the game",
        "imgPagin": "sliderWot/assets/nation/France/france-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/France/france-flag_pag.webp"
    },
    {
        "id": "slide-5",
        "nation": "U.K.",
        "quantity": "88",
        "type": "U.K. vehicles in the game",
        "technic": ["Churchill VII", "Centurion Mk. I", "Super Conqueror", "Tortoise, FV304"],
        "imgFlag": "sliderWot/assets/nation/GreatBritain/greatBritain-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/GreatBritain/greatBritain-flag.webp",
        "imgTanks": "sliderWot/assets/nation/GreatBritain/greatBritain-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/GreatBritain/greatBritain-tanks.webp",
        "altTanks": "British cars in the game",
        "imgPagin": "sliderWot/assets/nation/GreatBritain/greatBritain-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/GreatBritain/greatBritain-flag_pag.webp"
    },
    {
        "id": "slide-6",
        "nation": "Czechoslovakia",
        "quantity": "19",
        "type": "Czechoslovakian vehicles in the game",
        "technic": ["Škoda T 25", "Konštrukta T-34/100", "TVP T 50/51", "TVP VTU Koncept", " LT vz. 38"],
        "imgFlag": "sliderWot/assets/nation/Сzechoslovakia/czech-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Сzechoslovakia/czech-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Сzechoslovakia/czech-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Сzechoslovakia/czech-tanks.webp",
        "altTanks": "Czechoslovak cars in the game",
        "imgPagin": "sliderWot/assets/nation/Сzechoslovakia/czech-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Сzechoslovakia/czech-flag_pag.webp"
    },
    {
        "id": "slide-7",
        "nation": "China",
        "quantity": "47",
        "type": "Chinese vehicles in the game",
        "technic": ["WZ-132", "WZ-111", "WZ-111 model 5A", "T-34-1", "WZ-111-1G FT"],
        "imgFlag": "sliderWot/assets/nation/China/china-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/China/china-flag.webp",
        "imgTanks": "sliderWot/assets/nation/China/china-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/China/china-tanks.webp",
        "altTanks": "Chinese cars in the game",
        "imgPagin": "sliderWot/assets/nation/China/china-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/China/china-flag_pag.webp"
    },
    {
        "id": "slide-8",
        "nation": "Japan",
        "quantity": "26",
        "type": "Japanese vehicles in the game",
        "technic": ["Type 61", "O-I", "Type 5 Heavy", "Type 5 Chi-Ri", "STB-1"],
        "imgFlag": "sliderWot/assets/nation/Japan/japan-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Japan/japan-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Japan/japan-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Japan/japan-tanks.webp",
        "altTanks": "Japanese cars in the game",
        "imgPagin": "sliderWot/assets/nation/Japan/japan-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Japan/japan-flag_pag.webp"
    },
    {
        "id": "slide-9",
        "nation": "Sweden",
        "quantity": "32",
        "type": "Swedish vehicles in the game",
        "technic": ["Emil II", "UDES 03", "Kranvagn", "Strv 103B", "Strv 74"],
        "imgFlag": "sliderWot/assets/nation/Sweden/sweden-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Sweden/sweden-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Sweden/sweden-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Sweden/sweden-tanks.webp",
        "altTanks": "Swedish cars in the game",
        "imgPagin": "sliderWot/assets/nation/Sweden/sweden-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Sweden/sweden-flag_pag.webp"
    },
    {
        "id": "slide-10",
        "nation": "Poland",
        "quantity": "21",
        "type": "Polish vehicles in the game",
        "technic": ["Pudel", "45TP Habicha", "60TP Lewandowskiego", " 50TP prototyp", "50TP Tyszkiewicza"],
        "imgFlag": "sliderWot/assets/nation/Poland/Poland-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Poland/Poland-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Poland/poland-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Poland/poland-tanks.webp",
        "altTanks": "Polish cars in the game",
        "imgPagin": "sliderWot/assets/nation/Poland/poland-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Poland/poland-flag_pag.webp"
    },
    {
        "id": "slide-11",
        "nation": "Italy",
        "quantity": "25",
        "type": "Italian vehicles in the game",
        "technic": ["P26/40", "Prototipo Standard B", "Progetto M40 mod. 65", "P.44 Pantera", "P.43 bis"],
        "imgFlag": "sliderWot/assets/nation/Italy/Italy-flag.png",
        "imgFlagWebP": "sliderWot/assets/nation/Italy/Italy-flag.webp",
        "imgTanks": "sliderWot/assets/nation/Italy/italy-tanks.png",
        "imgTanksWebP": "sliderWot/assets/nation/Italy/italy-tanks.webp",
        "altTanks": "Italian cars in the game",
        "imgPagin": "sliderWot/assets/nation/Italy/italy-flag_pag.png",
        "imgPaginWebP": "sliderWot/assets/nation/Italy/italy-flag_pag.webp"
    }
]